#!/bin/python3
import sys, os, math

###
### CONFIGURATION - change these ###
###

CONFIG_LOCATION = '/home/rpj/.workhorse'

###
###
###

projects = []

class Project():
    def __init__(self, name, h, m):
        self.name    = name
        self.hours   = h
        self.minutes = m

    def __str__(self):
        return '%s %dH %dM' % (self.name, self.hours, self.minutes)

    def add(self, hours, minutes):
        self.minutes    += minutes
        hours           += math.floor(self.minutes / 60.0)
        self.minutes    = self.minutes % 60

        self.hours      += hours

    def save_str(self):
        return '%s:%dH:%dM\n' % (self.name, self.hours, self.minutes)

def load_project(parts):
    new = Project(parts[0], int(parts[1][:-1]), int(parts[2][:-2]))
    projects.append(new)

def load_projects():
    f           = open(CONFIG_LOCATION, 'r')
    found_data  = False

    for line in f:
        parts = line.split(':')

        if found_data:
            load_project(parts)
        elif '%% data' in parts[0]:
            found_data = True

    f.close()

def show_projects():
    for i in range(len(projects)):
        print('%d. %s' % (i+1, projects[i]))

def get_project_from_arg(arg):
    if arg.isnumeric():
        index = int(arg) - 1
        return projects[index]
    else:
        for project in projects:
            if project.name.startswith(arg):
                return project

    return None
    # raise Exception('no such project: "%s"' % (arg))

def show_project(arg):
    project = get_project_from_arg(arg)

    if project == None:
        print('no such project')
        return

    print(project)

def add_hours(name, hours, minutes):
    project = get_project_from_arg(name)

    # new project
    if project == None:
        projects.append(Project(name, hours, minutes))
    else:
        project.add(hours, minutes)

def save():
    os.system('cp %s %s' % (CONFIG_LOCATION, CONFIG_LOCATION+'.bak'))
    f = open(CONFIG_LOCATION, 'w')

    f.write('%% data\n')

    for project in projects:
        f.write(project.save_str())

    f.close()

def get_args(argv):
    project_name = ''
    hours = 0
    minutes = 0

    for arg in argv[1:]:
        number = arg.rstrip()[:-1]

        if ('H' in arg or 'h' in arg) and (number.isnumeric() or 
                (number[0] == '-' and number[1:].isnumeric())):
            hours   = int(number)
        elif ('M' in arg or 'm' in arg) and (number.isnumeric() or
                (number[0] == '-' and number[1:].isnumeric())):
            minutes = int(number)
        else:
            project_name += arg + ' '

    return (project_name.rstrip(), hours, minutes)

if __name__ == '__main__':
    load_projects()

    args = get_args(sys.argv)

    # show all projects
    if len(args[0]) == 0:
        show_projects()

    # show specific project
    elif args[1] == 0 and args[2] == 0:
        show_project(args[0])

    else:
        add_hours(args[0], args[1], args[2])
        show_project(args[0])

    save()
